# Mode similar to CUPS-RL

action_categories:
  # === Navigation actions ===
  movement_actions: True
  body_rotation_actions: True
  head_rotation_actions: False
  crouch_actions: False

  # === Object manipulation actions ===
  pickup_put_actions: True
  drop_actions: False
  throw_actions: False
  push_pull_actions: False
  hand_movement_actions: False

  # === Object interaction actions ===
  open_close_actions: True
  toggle_actions: False
  slice_actions: False
  useUp_actions: False
  liquid_interaction_actions: False
  break_actions: False
  clean_dirty_actions: False

action_parameters:
  manualInteract: False
  placeStationary: True

partial_openness: False
simple_movement_actions: False
