# Mode similar to CUPS-RL

# === Navigation actions ===
head_rotation_actions: False
crouch_actions: False

# === Object manipulation actions ===
drop_actions: False
throw_actions: False
push_pull_actions: False

# === Object interaction actions ===
toggle_actions: False
liquid_interaction_actions: False
slice_actions: False
useUp_actions: False

partial_openness: False # If True, objects can be opened partially with a parameter