# Navigation mode config

# === Navigation actions ===
head_rotation_actions: False
crouch_actions: False

# === Object manipulation actions ===
pickup_put_actions: False
drop_actions: False
throw_actions: False
push_pull_actions: False

# === Object interaction actions ===
open_close_actions: False
toggle_actions: False
liquid_interaction_actions: False
slice_actions: False
useUp_actions: False
