wandb:
  project: rl_thor_benchmark
  sync_tensorboard: true
  monitor_gym: true
  save_code: true
  sb3_callback:
    verbose: 2
    model_save_freq: 100_000
    gradient_save_freq: 10_000

evaluation:
  nb_episodes: 10
  frequency: 2048
  deterministic: true
  verbose: 1

video_recorder:
  frequency: 16_384
  length: 500
  prefix: "rl-video"
