# General config file for ai2thor RL benchmark.

seed: 1
max_episode_steps: 1000
environment_mode: default # navigation_only, cups_like, alfred_like, default, full_with_hand_movement

discrete_actions: True # If True, all actions requiring a parameter will be discretized
target_closest_object: True # If True, the closest operable object to the agent will be used as target for object interaction actions (e.g. pickup, open, etc.)

use_done_action: False # If True, the agent has to explicitly end the episode with the done action after completing the task  # !! Not implemented yet !!

random_agent_spawn: False # If True, the agent will spawn at a random location and rotation at the beginning of each episode
random_object_spawn: False # If True, pickupable objects will spawn at random locations at the beginning of each episode
material_randomization: False # If True, the materials of the objects will be randomized at the beginning of each episode
lighting_randomization: False # If True, the lighting conditions will be randomized at the beginning of each episode
color_randomization: False # If True, the colors of the objects will be randomized at the beginning of each episode  # Note: Not realistic


grayscale: False # !! Not implemented yet !!

action_parameters: # ** Not supposed to be modified **
  forceAction: False # If True, some actions will be performed even if they are not valid because it would cause clipping, because the target object is not visible, etc.
  forceVisible: True # If True, hand movement actions will fail if the target object is not visible

controller_parameters:
  platform: null # set to "CloudRendering" for headless cloud rendering

  visibilityDistance: 1.5

  # Step sizes
  gridSize: 0.25 # ** Don't affect the moveMagnitude of MoveAhead, MoveBack, MoveLeft, MoveRight here
  snapToGrid: True
  # rotateStepDegrees: 90 # TODO: Remove (deprecated)

  # Image modalities  # !! Not implemented yet !!
  # renderDepthImage: False
  # renderInstanceSegmentation: False

  # Camera properties
  width: 300
  height: 300
  fieldOfView: 90
